name: Posthuman
baseurl: /posthumanco
markdown: redcarpet
pygments: true
permalink: blog/:title
paginate: 3
paginate_path: "blog/page:num"

exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']