name: Posthuman
baseurl: http://posthuman.co
markdown: redcarpet
pygments: true
permalink: blog/:title
paginate: 2
paginate_path: "blog/page:num"

exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']