name: Posthuman
baseurl: http://posthuman.co
markdown: redcarpet
pygments: true
# highlighter: pygments
permalink: blog/:title
paginate: 2
paginate_path: "blog/page:num"
# sass:
#     sass_dir: assets/css

exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']