name: Posthuman
host: localhost
port: 4000
baseurl: #/posthumanco
markdown: redcarpet
pygments: true
permalink: /blog/:title
paginate: 3
paginate_path: "page:num"

exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']